SELECT
	RTRIM(CTT010.CTT_CUSTO) AS 'CC',
	REPLACE(RTRIM(CTT010.CTT_XREGIO),'_',' ') AS 'REGIONAL',
	REPLACE(RTRIM(CTT010.CTT_DESC01),'  ',' ') AS 'CENTRO DE CUSTO',
	IIF(
			REPLACE(REPLACE(RTRIM(CTT_XPOLO),'_',' '),'POLO ', '')=REPLACE(RTRIM(CTT010.CTT_XREGIO),'_',' '),
			REPLACE(REPLACE(RTRIM(CTT_XPOLO),'_',' '),'POLO ', ''),
			REPLACE(REPLACE(REPLACE(RTRIM(CTT_XPOLO),'_',' '),'POLO ', ''), REPLACE(RTRIM(CTT010.CTT_XREGIO),'_',' ')+' ', '')
	) AS 'POLO',
	REPLACE(REPLACE(REPLACE(RTRIM(CTT_XSERVI),'_',' '),'SERVICO ', ''),REPLACE(RTRIM(CTT010.CTT_XREGIO),'_',' ')+' ', '') AS 'SERVIÇO'
FROM PROTHEUS.dbo.CTT010 CTT010
WHERE 
	CTT010.D_E_L_E_T_ <> '*' 