SELECT
	RTRIM(CTD010.CTD_ITEM) AS 'PLACA',
	RTRIM(CTD010.CTD_DESC01) AS 'DESCRIÇÃO',
	CTD010.CTD_CRGNV2 AS 'CC',
	RTRIM(CTT010.CTT_DESC01) AS 'DESCRIÇÃO CENTRO DE CUSTO',
	RTRIM(CTD010.CTD_URSINC) AS 'USUÁRIO INCLUSÃO',
	
	CTD010.CTD_FABRIC+' - '+
		(
			SELECT TOP 1 RTRIM(SX5010.X5_DESCRI)
			FROM PROTHEUS.dbo.SX5010 SX5010
			WHERE
				SX5010.X5_TABELA='ZY' 
				AND CTD010.CTD_FABRIC=X5_CHAVE
		) AS 'FABRICANTE',
	
	CASE WHEN CTD010.CTD_SEGURO=1 THEN 'SIM' ELSE 'NÃO' END AS 'SEGURO',
	CASE WHEN SA2010.A2_COD='      ' THEN '' ELSE SA2010.A2_COD+' - '+SA2010.A2_NREDUZ END AS 'SEGURADORA',
	
	CASE
		WHEN (CTD010.CTD_ANO='' AND CTD010.CTD_MODELO='')
			THEN ''
		ELSE RTRIM(CTD010.CTD_ANO+'/'+CTD010.CTD_MODELO)
	END AS 'ANO/MODELO',
	
	RTRIM(CTD010.CTD_CATEG)+' - '+
		(
			SELECT TOP 1 RTRIM(SX5010.X5_DESCRI)
			FROM PROTHEUS.dbo.SX5010 SX5010
			WHERE
				SX5010.X5_TABELA='ZV' 
				AND CTD010.CTD_CATEG=X5_CHAVE
		) AS 'CATEGORIA',
		
	RTRIM(CTD010.CTD_CHASS) AS 'NUM CHASSI',
	RTRIM(CTD010.CTD_RENAV) AS 'NUM RENAVAM',
	CTD010.CTD_VALCOM AS 'VAL COMPRA',
	CTD010.CTD_EST AS 'UF',
	RTRIM(CTD010.CTD_DESPAC) AS 'DESPACHANTE',
	RTRIM(CTD010.CTD_HISTOR) AS 'HISTORICO',
	CASE WHEN CTD010.CTD_ALIENA=1 THEN 'SIM' ELSE 'NÃO' END AS 'ALIENADO',
	CTD010.CTD_VLVEND AS 'VALOR VENDA',
	
	Case RTrim(Coalesce(CTD010.CTD_DTVEND,'')) WHEN ''  THEN Null ELSE convert(datetime, CTD010.CTD_DTVEND, 112)END AS 'DT VENDA',
	Case RTrim(Coalesce(CTD010.CTD_DTSEGU,'')) WHEN ''  THEN Null ELSE convert(datetime, CTD010.CTD_DTSEGU, 112)END AS 'DT INCLU SEG',
	Case RTrim(Coalesce(CTD010.CTD_DTFIMS,'')) WHEN ''  THEN Null ELSE convert(datetime, CTD010.CTD_DTFIMS, 112)END AS 'DT FIM SEG',
	Case RTrim(Coalesce(CTD010.CTD_DTCMP,'')) WHEN ''  THEN Null ELSE convert(datetime, CTD010.CTD_DTCMP, 112)END AS 'DT COMPRA',
	Case RTrim(Coalesce(CTD010.CTD_DATRDO,'')) WHEN ''  THEN Null ELSE convert(datetime, CTD010.CTD_DATRDO, 112)END AS 'DT REC DOC',
	Case RTrim(Coalesce(CTD010.CTD_DTFINA,'')) WHEN ''  THEN Null ELSE convert(datetime, CTD010.CTD_DTFINA, 112)END AS 'DT FINA INI',
	Case RTrim(Coalesce(CTD010.CTD_DTFIMF,'')) WHEN ''  THEN Null ELSE convert(datetime, CTD010.CTD_DTFIMF, 112)END AS 'DT FINA FIM'
FROM PROTHEUS.dbo.CTD010 CTD010
	LEFT JOIN PROTHEUS.dbo.CTT010 CTT010 ON CTD010.CTD_CRGNV2=CTT010.CTT_CUSTO
	LEFT JOIN PROTHEUS.dbo.SA2010 SA2010 ON SA2010.A2_COD=CTD010.CTD_SEGURD
WHERE
	CTD010.D_E_L_E_T_<>'*'
	AND CTD010.CTD_BLOQ<>1
ORDER BY
	CTD010.CTD_ITEM