--Consulta realizada por terceiro

--#######		TITULOS ATRAVES DE NFE QUE SOFRERAM FATURA #########
SELECT CCUSTO AS GERCCCOD,
	NATUREZA AS GERNATCOD,
	PREFIXO AS GERPREF,
	NUMERO AS GERNUM,
	TIPO AS GERTIPO,
	COD_FORNECEDOR AS GERCODFR,
	LOJA AS GERLOJ,
	NOMEFOR AS GERFORNOM,
	DT_EMISSAO AS GERDTEMS,
	VENCTO_REAL AS GERDTVCT,
	DT_BAIXA AS GERDTBX,
	ANO_BAIXA AS GERANO,
	MES_BAIXA AS GERMES,
	HISTORICO AS GERHIST,
	VALOR_ORIGINAL AS GERVLRORG,
	VALOR_PAGO AS GERVLRPG,
	ITEM_CTA AS GERITCT,
	CLASSE_VALOR AS GERCLVL,
	ORIGEM AS GERORIG,
	INFORMACOES_COMPL AS GERINFCP,
	RECNO AS R_E_C_N_O_,
	D1_PEDIDO AS GERNUMPC,
	C1_NUM AS GERNUMSC,
	CHAVE AS GERCHAVE,
	CHAVE2 AS GERCHAVEORIG,
	PARCELA AS GERPARCEL
--,REF
FROM (
	SELECT
       (
            CASE
                WHEN D1_CC = '' AND C7_CC <> ''
                    THEN C7_CC
                WHEN D1_CC = '' AND C7_CC = ''
                    THEN C1_CC
                ELSE D1_CC
            END
        ) AS CCUSTO,
		SE5.E5_NATUREZ AS NATUREZA,
		SE5.E5_PREFIXO AS PREFIXO,
		SE5.E5_NUMERO AS NUMERO,
		SE5.E5_PARCELA AS PARCELA,
		SE5.E5_TIPO AS TIPO,
		SE5.E5_CLIFOR AS COD_FORNECEDOR,
		SE5.E5_LOJA AS LOJA,
		SA2.A2_NOME AS NOMEFOR,
		SE2FAT.E2_EMISSAO AS DT_EMISSAO,
		SE2FAT.E2_VENCREA AS VENCTO_REAL,
		SE5.E5_DATA AS DT_BAIXA,
		YEAR(SE5.E5_DATA) AS ANO_BAIXA,
		MONTH(SE5.E5_DATA) AS MES_BAIXA,
		SE2FAT.E2_HIST AS HISTORICO,
		SE2FAT.E2_INFCOMP AS INFORMACOES_COMPL,
		ROUND((SE5.E5_VALOR * ((D1_TOTAL - (D1_VALDESC + SE2FAT.E2_IRRF + SE2FAT.E2_PIS + SE2FAT.E2_COFINS + SE2FAT.E2_CSLL)) / SE2FAT.E2_VALOR)), 2) AS VALOR_ORIGINAL,
		SE5.E5_VALOR * (
			(D1_TOTAL - (D1_VALDESC + SE2FAT.E2_IRRF + SE2FAT.E2_PIS + SE2FAT.E2_COFINS + SE2FAT.E2_CSLL)) / (
				SELECT SUM(E2_VALOR)
				FROM PROTHEUS..SE2010 TMPSE2 WITH (NOLOCK)
				WHERE TMPSE2.D_E_L_E_T_ = ''
					AND E2_NUM = SE5.E5_NUMERO
					AND E2_PREFIXO = SE5.E5_PREFIXO
					AND E2_FORNECE = SE5.E5_CLIFOR
					AND E2_FILORIG = SE5.E5_FILORIG
				)
			) AS VALOR_PAGO,
		D1_ITEMCTA AS ITEM_CTA,
		(
			CASE
				WHEN D1_CLVL = ''
					AND C7_CLVL <> ''
					THEN C7_CLVL
				WHEN D1_CLVL = ''
					AND C7_CLVL = ''
					THEN C1_CLVL
				ELSE D1_CLVL
				END
			) AS CLASSE_VALOR,
		(
			CASE
				WHEN LEFT(SE2.E2_ORIGEM, 4) = 'MATA'
					THEN 'COMPRAS'
				END
			) AS ORIGEM,
		(
			(
				CASE
					WHEN SD1.R_E_C_N_O_ IS NULL
						THEN 0
					ELSE SD1.R_E_C_N_O_
					END
				) + (
				CASE
					WHEN SE2.R_E_C_N_O_ IS NULL
						THEN 0
					ELSE SE2.R_E_C_N_O_
					END
				) + (
				CASE
					WHEN SE2FAT.R_E_C_N_O_ IS NULL
						THEN 0
					ELSE SE2FAT.R_E_C_N_O_
					END
				) + (
				CASE
					WHEN SE5.R_E_C_N_O_ IS NULL
						THEN 0
					ELSE SE5.R_E_C_N_O_
					END
				) + (
				CASE
					WHEN SC1.R_E_C_N_O_ IS NULL
						THEN 0
					ELSE SC1.R_E_C_N_O_
					END
				) + (
				CASE
					WHEN SC7.R_E_C_N_O_ IS NULL
						THEN 0
					ELSE SC7.R_E_C_N_O_
					END
				) + (
				CASE
					WHEN SA2.R_E_C_N_O_ IS NULL
						THEN 0
					ELSE SA2.R_E_C_N_O_
					END
				) + convert(INT, SE5.E5_DATA)
			) AS RECNO,
		D1_PEDIDO,
		C1_NUM,
		CHAVE = SE2FAT.E2_FILORIG + '-' + SE2FAT.E2_PREFIXO + '-' + SE2FAT.E2_NUM + '-' + SE2FAT.E2_PARCELA + '-' + SE2FAT.E2_TIPO,
		CHAVE2 = SD1.D1_FILIAL + '-' + SD1.D1_SERIE + '-' + SD1.D1_DOC + '-' + '' + '-' + SE2.E2_TIPO + '-' + SD1.D1_ITEM,
		REF = 'COMPRAS-FATURA',
		SE2.E2_ORIGEM AS SE2_ORIGEM
	FROM PROTHEUS..SE5010 SE5 WITH (NOLOCK)
	LEFT JOIN PROTHEUS..SE2010 SE2FAT WITH (NOLOCK)
		ON SE5.E5_PREFIXO = SE2FAT.E2_PREFIXO
			AND SE5.E5_CLIFOR = SE2FAT.E2_FORNECE
			AND SE5.E5_LOJA = SE2FAT.E2_LOJA
			AND SE5.E5_NUMERO = SE2FAT.E2_NUM
			AND SE2FAT.E2_PARCELA = SE5.E5_PARCELA
			AND SE2FAT.E2_FILORIG = SE5.E5_FILORIG
	LEFT JOIN PROTHEUS..SE2010 SE2 WITH (NOLOCK)
		ON SE2.E2_FATPREF = SE2FAT.E2_PREFIXO
			AND SE2.E2_FATURA = SE2FAT.E2_NUM
			AND SE2.E2_TIPOFAT = SE2FAT.E2_TIPO
			AND SE2.E2_FATFOR = SE2FAT.E2_FORNECE
			AND SE2.E2_FATLOJ = SE2FAT.E2_LOJA
	LEFT JOIN PROTHEUS..SD1010 SD1 WITH (NOLOCK)
		ON SE2.E2_FILORIG = D1_FILIAL
			AND SE2.E2_NUM = D1_DOC
			AND SE2.E2_FORNECE = D1_FORNECE
			AND SE2.E2_LOJA = D1_LOJA
			AND SE2.E2_PREFIXO = D1_SERIE
	LEFT JOIN PROTHEUS..SC7010 SC7 WITH (NOLOCK)
		ON D1_FILIAL = C7_FILIAL
			AND D1_PEDIDO = C7_NUM
			AND D1_ITEMPC = C7_ITEM
			AND D1_FORNECE = C7_FORNECE
			AND D1_LOJA = C7_LOJA
	LEFT JOIN PROTHEUS..SC1010 SC1 WITH (NOLOCK)
		ON C7_NUMSC = C1_NUM
			AND C7_ITEMSC = C1_ITEM
			AND C1_FILIAL = C7_FILIAL
	LEFT JOIN PROTHEUS..SA2010 SA2 WITH (NOLOCK)
		ON A2_COD = SE5.E5_CLIFOR
			AND SE5.E5_LOJA = A2_LOJA
	WHERE ISNULL(SC1.D_E_L_E_T_, '') = ''
		AND ISNULL(SC7.D_E_L_E_T_, '') = ''
		AND ISNULL(SD1.D_E_L_E_T_, '') = ''
		AND ISNULL(SE2.D_E_L_E_T_, '') = ''
		AND ISNULL(SE2FAT.D_E_L_E_T_, '') = ''
		AND ISNULL(SE5.D_E_L_E_T_, '') = ''
		AND SE2FAT.E2_FATURA <> ''
		AND LEFT(SE2.E2_ORIGEM, 4) = 'MATA'
		AND SE5.E5_TIPODOC IN (
			'VL',
			'CP'
			)
		AND SE5.E5_MOTBX IN (
			'NOR',
			'DEB',
			'CMP'
			)
		AND SE2.E2_TIPO <> 'TX'
		AND SE5.E5_DTCANBX = ''
		AND LEFT(SE2.E2_ORIGEM, 4) <> 'MATA'
		AND SE5.E5_SEQ = (
			SELECT MAX(E5_SEQ)
			FROM PROTHEUS..SE5010 SE5SEQ WITH (NOLOCK)
			WHERE SE5SEQ.D_E_L_E_T_ = ''
				AND SE5SEQ.R_E_C_N_O_ = SE5.R_E_C_N_O_
			)

	UNION ALL

	--#######		TITULOS ATRAVES DE NFE QUE NÃO SOFRERAM FATURA #########
	SELECT (
			CASE
				WHEN D1_CC = ''
					AND C7_CC <> ''
					THEN C7_CC
				WHEN D1_CC = ''
					AND C7_CC = ''
					THEN C1_CC
				ELSE D1_CC
				END
			) AS CCUSTO,
		SE5.E5_NATUREZ AS NATUREZA,
		SE5.E5_PREFIXO AS PREFIXO,
		SE5.E5_NUMERO AS NUMERO,
		SE5.E5_PARCELA AS PARCELA,
		SE5.E5_TIPO AS TIPO,
		SE5.E5_CLIFOR AS COD_FORNECEDOR,
		SE5.E5_LOJA AS LOJA,
		SA2.A2_NOME AS NOMEFOR,
		D1_EMISSAO AS DT_EMISSAO,
		SE2.E2_VENCREA AS VENCTO_REAL,
		SE5.E5_DATA AS DT_BAIXA,
		YEAR(SE5.E5_DATA) AS ANO_BAIXA,
		MONTH(SE5.E5_DATA) AS MES_BAIXA,
		SE2.E2_HIST AS HISTORICO,
		SE2.E2_INFCOMP AS INFORMACOES_COMPL,
		D1_TOTAL - (D1_VALDESC + SE2.E2_IRRF + SE2.E2_PIS + SE2.E2_COFINS + SE2.E2_CSLL) AS VALOR_ORIGINAL,
		SE5.E5_VALOR * (
			(D1_TOTAL - (D1_VALDESC + SE2.E2_IRRF + SE2.E2_PIS + SE2.E2_COFINS + SE2.E2_CSLL)) / (
				SELECT SUM(E2_VALOR)
				FROM PROTHEUS..SE2010 TMPSE2 WITH (NOLOCK)
				WHERE TMPSE2.D_E_L_E_T_ = ''
					AND E2_NUM = SE5.E5_NUMERO
					AND E2_PREFIXO = SE5.E5_PREFIXO
					AND E2_FORNECE = SE5.E5_CLIFOR
					AND E2_FILORIG = SE5.E5_FILORIG
				)
			) AS VALOR_PAGO,
		D1_ITEMCTA AS ITEM_CTA,
		(
			CASE
				WHEN D1_CLVL = ''
					AND C7_CLVL <> ''
					THEN C7_CLVL
				WHEN D1_CLVL = ''
					AND C7_CLVL = ''
					THEN C1_CLVL
				ELSE D1_CLVL
				END
			) AS CLASSE_VALOR,
		(
			CASE
				WHEN LEFT(SE2.E2_ORIGEM, 4) = 'MATA'
					THEN 'COMPRAS'
				END
			) AS ORIGEM,
		(
			CASE
				WHEN SD1.R_E_C_N_O_ IS NULL
					THEN 0
				ELSE SD1.R_E_C_N_O_
				END
			) + (
			CASE
				WHEN SE2.R_E_C_N_O_ IS NULL
					THEN 0
				ELSE SE2.R_E_C_N_O_
				END
			) + (
			CASE
				WHEN SE5.R_E_C_N_O_ IS NULL
					THEN 0
				ELSE SE5.R_E_C_N_O_
				END
			) + (
			CASE
				WHEN SC1.R_E_C_N_O_ IS NULL
					THEN 0
				ELSE SC1.R_E_C_N_O_
				END
			) + (
			CASE
				WHEN SC7.R_E_C_N_O_ IS NULL
					THEN 0
				ELSE SC7.R_E_C_N_O_
				END
			) + (
			CASE
				WHEN SA2.R_E_C_N_O_ IS NULL
					THEN 0
				ELSE SA2.R_E_C_N_O_
				END
			) + convert(INT, SE5.E5_DATA) AS RECNO,
		D1_PEDIDO,
		C1_NUM,
		CHAVE = SE2.E2_FILORIG + '-' + SE2.E2_PREFIXO + '-' + SE2.E2_NUM + '-' + SE2.E2_PARCELA + '-' + SE2.E2_TIPO + '-' + SD1.D1_ITEM,
		CHAVE2 = '',
		REF = 'COMPRAS-NOTFATURA',
		SE2.E2_ORIGEM AS SE2_ORIGEM
	FROM PROTHEUS..SE5010 SE5 WITH (NOLOCK)
	LEFT JOIN PROTHEUS..SE2010 SE2 WITH (NOLOCK)
		ON SE5.E5_PREFIXO = SE2.E2_PREFIXO
			AND SE5.E5_CLIFOR = SE2.E2_FORNECE
			AND SE5.E5_LOJA = SE2.E2_LOJA
			AND SE5.E5_NUMERO = SE2.E2_NUM
			AND SE5.E5_PARCELA = SE2.E2_PARCELA
			AND SE5.E5_FILORIG = SE2.E2_FILORIG
			AND SE5.E5_FILIAL = SE2.E2_FILIAL
			AND SE5.E5_TIPO = SE2.E2_TIPO
	LEFT JOIN PROTHEUS..SD1010 SD1 WITH (NOLOCK)
		ON SE2.E2_FILORIG = D1_FILIAL
			AND SE2.E2_NUM = D1_DOC
			AND SE2.E2_FORNECE = D1_FORNECE
			AND SE2.E2_LOJA = D1_LOJA
			AND SE2.E2_PREFIXO = D1_SERIE
	LEFT JOIN PROTHEUS..SC7010 SC7 WITH (NOLOCK)
		ON D1_FILIAL = C7_FILIAL
			AND D1_PEDIDO = C7_NUM
			AND D1_ITEMPC = C7_ITEM
			AND D1_FORNECE = C7_FORNECE
			AND D1_LOJA = C7_LOJA
	LEFT JOIN PROTHEUS..SC1010 SC1 WITH (NOLOCK)
		ON C7_NUMSC = C1_NUM
			AND C7_ITEMSC = C1_ITEM
			AND C1_FILIAL = C7_FILIAL
	LEFT JOIN PROTHEUS..SA2010 SA2 WITH (NOLOCK)
		ON A2_COD = SE5.E5_CLIFOR
			AND SE5.E5_LOJA = A2_LOJA
	WHERE ISNULL(SC1.D_E_L_E_T_, '') = ''
		AND ISNULL(SC7.D_E_L_E_T_, '') = ''
		AND ISNULL(SD1.D_E_L_E_T_, '') = ''
		AND ISNULL(SE2.D_E_L_E_T_, '') = ''
		AND ISNULL(SE5.D_E_L_E_T_, '') = ''
		AND ISNULL(SA2.D_E_L_E_T_, '') = ''
		AND (
			SE2.E2_FATURA = ''
			OR SE2.E2_FATURA = 'NOTFAT'
			)
		AND LEFT(SE2.E2_ORIGEM, 4) = 'MATA'
		AND SE5.E5_TIPODOC IN (
			'BA',
			'VL',
			'CP'
			)
		AND SE5.E5_MOTBX IN (
			'NOR',
			'DEB',
			'CMP'
			)
		AND SE2.E2_TIPO <> 'TX'
		AND SE5.E5_SITUACA <> 'C'
		AND SE5.E5_DTCANBX = ''
		AND SE5.E5_SEQ = (
			SELECT MAX(E5_SEQ)
			FROM PROTHEUS..SE5010 SE5SEQ WITH (NOLOCK)
			WHERE SE5SEQ.D_E_L_E_T_ = ''
				AND SE5SEQ.R_E_C_N_O_ = SE5.R_E_C_N_O_
			)

	UNION ALL

	--#######		TITULOS GERADOS DIRETAMENTE NO FINANCEIRO SEM FATURAS	  #########
	SELECT E2_CCD AS CCUSTO,
		SE5.E5_NATUREZ AS NATUREZA,
		SE5.E5_PREFIXO AS PREFIXO,
		SE5.E5_NUMERO AS NUMERO,
		SE5.E5_TIPO AS TIPO,
		SE5.E5_PARCELA AS PARCELA,
		SE5.E5_CLIFOR AS COD_FORNECEDOR,
		SE5.E5_LOJA AS LOJA,
		SA2.A2_NOME AS NOMEFOR,
		E2_EMISSAO AS DT_EMISSAO,
		SE5.E5_VENCTO AS VENCTO_REAL,
		SE5.E5_DATA AS DT_BAIXA,
		YEAR(SE5.E5_DATA) AS ANO_BAIXA,
		MONTH(SE5.E5_DATA) AS MES_BAIXA,
		SE2.E2_HIST AS HISTORICO,
		E2_INFCOMP AS INFORMACOES_COMPL,
		E2_VALOR AS VALOR_ORIGINAL,
		E5_VALOR AS VALOR_PAGO,
		E2_ITEMCTA AS ITEM_CTA,
		SE2.E2_CLVL AS CLASSE_VALOR,
		(
			CASE
				WHEN LEFT(E2_ORIGEM, 4) = 'FINA'
					THEN 'FINANCEIRO'
				ELSE 'FOLHA'
				END
			) AS ORIGEM,
		(
			CASE
				WHEN SE2.R_E_C_N_O_ IS NULL
					THEN 0
				ELSE SE2.R_E_C_N_O_
				END
			) + (
			CASE
				WHEN SE5.R_E_C_N_O_ IS NULL
					THEN 0
				ELSE SE5.R_E_C_N_O_
				END
			) + (
			CASE
				WHEN SA2.R_E_C_N_O_ IS NULL
					THEN 0
				ELSE SA2.R_E_C_N_O_
				END
			) + convert(INT, SE5.E5_DATA) AS RECNO,
		D1_PEDIDO = '',
		C1_NUM = '',
		CHAVE = SE2.E2_FILORIG + '-' + SE2.E2_PREFIXO + '-' + SE2.E2_NUM + '-' + SE2.E2_PARCELA + '-' + SE2.E2_TIPO,
		CHAVE2 = '',
		REF = 'FINANCEIRO-NOTFATURA',
		SE2.E2_ORIGEM AS SE2_ORIGEM
	FROM PROTHEUS..SE5010 SE5 WITH (NOLOCK)
	LEFT JOIN PROTHEUS..SE2010 SE2 WITH (NOLOCK)
		ON E5_PREFIXO = E2_PREFIXO
			AND E5_CLIFOR = E2_FORNECE
			AND E5_LOJA = E2_LOJA
			AND E5_NUMERO = E2_NUM
			AND E2_PARCELA = E5_PARCELA
			AND E2_FILORIG = E5_FILORIG
			AND E2_FILIAL = E5_FILIAL
	LEFT JOIN PROTHEUS..SA2010 SA2 WITH (NOLOCK)
		ON A2_COD = SE5.E5_CLIFOR
			AND SE5.E5_LOJA = A2_LOJA
	WHERE ISNULL(SE2.D_E_L_E_T_, '') = ''
		AND ISNULL(SA2.D_E_L_E_T_, '') = ''
		AND ISNULL(SE5.D_E_L_E_T_, '') = ''
		AND E2_FATURA = ''
		AND (
			LEFT(SE2.E2_ORIGEM, 4) <> ('MATA')
			AND SE2.E2_ORIGEM NOT IN (
				'FINA565',
				'FINA290'
				)
			)
		AND SE5.E5_TIPODOC IN (
			'BA',
			'VL',
			'CP'
			)
		AND SE5.E5_MOTBX IN (
			'NOR',
			'DEB',
			'CMP'
			)
		AND SE5.E5_DTCANBX = ''
		AND SE5.E5_SITUACA <> 'C'
		AND SE5.E5_SEQ = (
			SELECT MAX(E5_SEQ)
			FROM PROTHEUS..SE5010 SE5SEQ WITH (NOLOCK)
			WHERE SE5SEQ.D_E_L_E_T_ = ''
				AND SE5SEQ.R_E_C_N_O_ = SE5.R_E_C_N_O_
			)

	UNION ALL

	--#######		TITULOS GERADOS DIRETAMENTE NO FINANCEIRO COM FATURAS	  #########
	SELECT (
			CASE
				WHEN SE2FAT.E2_CCD = ''
					THEN SE2.E2_CCD
				ELSE SE2FAT.E2_CCD
				END
			) AS CCUSTO,
		SE5.E5_NATUREZ AS NATUREZA,
		SE5.E5_PREFIXO AS PREFIXO,
		SE5.E5_NUMERO AS NUMERO,
		SE5.E5_PARCELA AS PARCELA,
		SE5.E5_TIPO AS TIPO,
		SE5.E5_CLIFOR AS COD_FORNECEDOR,
		SE5.E5_LOJA AS LOJA,
		SA2.A2_NOME AS NOMEFOR,
		SE2FAT.E2_EMISSAO AS DT_EMISSAO,
		SE5.E5_VENCTO AS VENCTO_REAL,
		SE5.E5_DATA AS DT_BAIXA,
		YEAR(SE5.E5_DATA) AS ANO_BAIXA,
		MONTH(SE5.E5_DATA) AS MES_BAIXA,
		SE2FAT.E2_HIST AS HISTORICO,
		SE2FAT.E2_INFCOMP AS INFORMACOES_COMPL,
		SE2FAT.E2_VALOR AS VALOR_ORIGINAL,
		SE2FAT.E2_VALOR + SE2FAT.E2_ACRESC AS VALOR_PAGO,
		SE2FAT.E2_ITEMCTA AS ITEM_CTA,
		SE2FAT.E2_CLVL AS CLASSE_VALOR,
		(
			CASE
				WHEN LEFT(SE2FAT.E2_ORIGEM, 4) = 'FINA'
					THEN 'FINANCEIRO'
				ELSE 'FOLHA'
				END
			) AS ORIGEM,
		(
			CASE
				WHEN SE2FAT.R_E_C_N_O_ IS NULL
					THEN 0
				ELSE SE2FAT.R_E_C_N_O_
				END
			) + (
			CASE
				WHEN SE2.R_E_C_N_O_ IS NULL
					THEN 0
				ELSE SE2.R_E_C_N_O_
				END
			) + (
			CASE
				WHEN SE5.R_E_C_N_O_ IS NULL
					THEN 0
				ELSE SE5.R_E_C_N_O_
				END
			) + (
			CASE
				WHEN SA2.R_E_C_N_O_ IS NULL
					THEN 0
				ELSE SA2.R_E_C_N_O_
				END
			) + convert(INT, SE5.E5_DATA) AS RECNO,
		D1_PEDIDO = '',
		C1_NUM = '',
		CHAVE = SE2FAT.E2_FILORIG + '-' + SE2FAT.E2_PREFIXO + '-' + SE2FAT.E2_NUM + '-' + SE2FAT.E2_PARCELA + '-' + SE2FAT.E2_TIPO,
		CHAVE2 = SE2.E2_FILORIG + '-' + SE2.E2_PREFIXO + '-' + SE2.E2_NUM + '-' + SE2.E2_PARCELA + '-' + SE2.E2_TIPO,
		REF = 'FINANCEIRO-FATURA',
		SE2.E2_ORIGEM AS SE2_ORIGEM
	FROM PROTHEUS..SE5010 SE5 WITH (NOLOCK)
	LEFT JOIN PROTHEUS..SE2010 SE2FAT WITH (NOLOCK)
		ON SE5.E5_PREFIXO = SE2FAT.E2_PREFIXO
			AND SE5.E5_CLIFOR = SE2FAT.E2_FORNECE
			AND SE5.E5_LOJA = SE2FAT.E2_LOJA
			AND SE5.E5_NUMERO = SE2FAT.E2_NUM
			AND SE2FAT.E2_PARCELA = SE5.E5_PARCELA
			AND SE2FAT.E2_FILORIG = SE5.E5_FILORIG
			AND SE2FAT.E2_FILIAL = SE5.E5_FILIAL
	LEFT JOIN PROTHEUS..SE2010 SE2 WITH (NOLOCK)
		ON SE2.E2_FATPREF = SE2FAT.E2_PREFIXO
			AND SE2.E2_FATURA = SE2FAT.E2_NUM
			AND SE2.E2_TIPOFAT = SE2FAT.E2_TIPO
			AND SE2.E2_FATFOR = SE2FAT.E2_FORNECE
			AND SE2.E2_FATLOJ = SE2FAT.E2_LOJA
	LEFT JOIN PROTHEUS..SA2010 SA2 WITH (NOLOCK)
		ON A2_COD = SE5.E5_CLIFOR
			AND SE5.E5_LOJA = A2_LOJA
	WHERE ISNULL(SE2.D_E_L_E_T_, '') = ''
		AND ISNULL(SA2.D_E_L_E_T_, '') = ''
		AND ISNULL(SE5.D_E_L_E_T_, '') = ''
		AND ISNULL(SE2FAT.D_E_L_E_T_, '') = ''
		AND (
			SE2FAT.E2_FATURA = 'NOTFAT'
			OR SE2FAT.E2_FATURA = ''
			)
		AND SE2FAT.E2_ORIGEM IN (
			'FINA290',
			'FINA565'
			)
		AND SUBSTRING(SE2.E2_ORIGEM, 1, 4) <> 'MATA'
		AND SE5.E5_TIPODOC IN (
			'BA',
			'VL',
			'CP'
			)
		AND SE5.E5_MOTBX IN (
			'NOR',
			'DEB',
			'CMP'
			)
		AND SE5.E5_DTCANBX = ''
		AND SE5.E5_SITUACA <> 'C'
		AND SE5.E5_SEQ = (
			SELECT MAX(E5_SEQ)
			FROM PROTHEUS..SE5010 SE5SEQ WITH (NOLOCK)
			WHERE SE5SEQ.D_E_L_E_T_ = ''
				AND SE5SEQ.R_E_C_N_O_ = SE5.R_E_C_N_O_
			)
	) AS TBGERENCIAL
