SELECT 
	CTH010.CTH_CLVL AS 'COD OBRA', 
	CTH010.CTH_DESC01 AS 'DESCRIÇÃO DA OBRA', 
	CTH010.CTH_ORCA AS 'VALOR ORÇADO', 
	CTH010.CTH_FILINC AS 'FILIAL', 
	CTH010.CTH_CLIENT AS 'CLIENTE',
	CASE WHEN CTH010.CTH_BLOQ=2 THEN 'DESBLOQUEADO' ELSE 'BLOQUEADO' END AS 'BLOQUEADO',
	Case RTrim(Coalesce(CTH010.CTH_DTEXIS,'')) WHEN ''  THEN Null ELSE convert(datetime, CTH010.CTH_DTEXIS, 112)END as 'DT INÍCIO',
	Case RTrim(Coalesce(CTH010.CTH_DTEXSF,'')) WHEN ''  THEN Null ELSE convert(datetime, CTH010.CTH_DTEXSF, 112)END as 'DT INÍCIO',
	RTRIM((
		SELECT TOP 1
			SA1010.A1_NREDUZ AS 'NOME'
		FROM 
		--TABELA DE MOVIMENTOS
		PROTHEUS.dbo.SA1010 SA1010
		WHERE 
			--IGNORAR DELETADOS
			(SA1010.D_E_L_E_T_<>'*') AND 
			--ESPECIFICA PERIODO
			(SA1010.A1_COD=CTH010.CTH_CLIENT)
	)) AS 'NOME CLIENTE'

FROM PROTHEUS.dbo.CTH010 CTH010

WHERE
	(CTH010.D_E_L_E_T_<>'*') --AND
	--(CTH010.CTH_CLIENT NOT IN ('000075','000634', '000646'))