--PEGA O ANO E O MÊS ANTERIOR PARA REALIZAR ALGUNS CÁLCULOS
DECLARE @ANOMES varchar(6) = CONCAT(DATEPART(yyyy, DATEADD(m, -1, getdate())), RIGHT('00'+CAST(DATEPART(m, DATEADD(m, -1, getdate())) AS VARCHAR(2)),2));

SELECT
	SRA010.RA_FILIAL AS 'FILIAL',
	SRA010.RA_MAT AS 'NUMERO DA MATRICULA',
	RTRIM(SRA010.RA_CC) AS 'CODIGO DO CENTRO DE CUSTO',
	RTRIM(CTT010.CTT_DESC01) AS 'DESCRIÇÃO CENTRO DE CUSTO', 
	RTRIM(SRA010.RA_NOME) AS 'NOME DO FUNCIONARIO',
	SRA010.RA_CIC AS 'CPF DO FUNCIONARIO',
	RTRIM(SRA010.RA_ENDEREC) AS 'ENDERECO DO FUNCIONARIO',
	RTRIM(SRA010.RA_RG) AS 'RG - REGISTRO GERAL',
	RTRIM(SRA010.RA_NUMCP) AS 'CARTEIRA PROFISSIONAL',
	RTRIM(SRA010.RA_BAIRRO) AS 'BAIRRO',
	SRA010.RA_ESTADO AS 'ESTADO',
	RTRIM(SRA010.RA_MUNICIP) AS 'MUNICIPIO',
	SRA010.RA_NATURAL AS 'NATURALIDADE FUNCIONARIO',
	RTRIM(SRA010.RA_MAE) AS 'NOME DA MAE',
	RTRIM(SRA010.RA_PAI) AS 'NOME DO PAI',
	SRA010.RA_DDDCELU AS 'DDD DO CELULAR',
	RTRIM(SRA010.RA_NUMCELU) AS 'NUMERO DO CELULAR',
	CASE RTRIM(COALESCE(SRA010.RA_NASC,'')) WHEN ''  THEN NULL ELSE CONVERT(DATETIME, SRA010.RA_NASC, 112)END AS 'DATA DE NASCIMENTO',
	SRA010.RA_CEP AS 'CEP',
	SRA010.RA_SEXO AS 'SEXO DO FUNCIONARIO',
	SRA010.RA_ESTCIVI AS 'ESTADO CIVIL FUNCIONARIO',
	CASE RTRIM(COALESCE(SRA010.RA_ADMISSA,'')) WHEN ''  THEN NULL ELSE CONVERT(DATETIME, SRA010.RA_ADMISSA, 112)END AS 'DATA DE ADMISSAO',
	CASE RTRIM(COALESCE(SRA010.RA_DEMISSA,'')) WHEN ''  THEN NULL ELSE CONVERT(DATETIME, SRA010.RA_DEMISSA, 112)END AS 'DATA DE DEMISSAO',
	CASE RTRIM(COALESCE(SRA010.RA_VCTOEXP,'')) WHEN ''  THEN NULL ELSE CONVERT(DATETIME, SRA010.RA_VCTOEXP, 112)END AS 'VENCIMENTO DA EXPERIENCIA',
	CASE RTRIM(COALESCE(SRA010.RA_VCTEXP2,'')) WHEN ''  THEN NULL ELSE CONVERT(DATETIME, SRA010.RA_VCTEXP2, 112)END AS 'VCTO.EXPERIENCIA 2O PER.',
	SRA010.RA_BCDEPSA AS 'BANCO AG. DEP. DE SALARIO',
	SRA010.RA_CTDEPSA AS 'CONTA DEPOSITO DE SALARIO',
	CASE RTRIM(SRA010.RA_SITFOLH)
		WHEN 'A' THEN 'AFASTADO'
		WHEN 'D' THEN 'DEMITIDO'
		WHEN 'F' THEN 'FERIAS'
		WHEN 'T' THEN 'TRANSFERIDO'
		ELSE 'ATIVO'
	END AS 'SITUACAO NA FOLHA', 
	SRA010.RA_HRSMES AS 'QUANTIDADE DE HORAS MES',
	SRA010.RA_HRSEMAN AS 'QUANTIDADE HORAS SEMANAIS',
	SRA010.RA_CODFUNC AS 'CODIGO DA FUNCAO',
	RTRIM(SRJ010.RJ_DESC) AS 'DESC FUNÇÃO',
	CASE SRA010.RA_TPJORNA
		WHEN  '1' THEN 'SUBMETIDO A HORARIO DE TRABALHO'
		WHEN  '2' THEN 'ATIVIDADE EXTERNA ESPECIFICADA'
		WHEN  '2' THEN 'FUNÇÕES ESPECIFICADAS'
		ELSE 'ERRO'
	END AS 'TIPO JORNADA DE TRABALHO', 
	RCE010.RCE_MESDIS AS 'MÊS DISSIDIO',
	SRA010.RA_SALARIO AS 'SALARIO DO FUNCIONARIO',
	SRA010.RA_PERICUL AS 'HORAS PERICULOSIDADE',
	SRA010.RA_INSMIN AS 'HRS. INSULUBRIDADE MINIMA',
	SRA010.RA_INSMED AS 'HRS. INSALUBRIDADE MEDIA',
	SRA010.RA_INSMAX AS 'HRS. INSALUBRIDADE MAXIMA',
	RTRIM(SRA010.RA_CRACHA) AS 'NRO. DO CRACHA DO EMPREG.',
	RTRIM(SRA010.RA_BITMAP) AS 'FOTO',
	RTRIM(SRA010.RA_NOMECMP) AS 'NOME COMPLETO FUNCIONARIO',
	RTRIM(SR6010.R6_DESC) AS 'DESC TURNO TRABALHO',
	SRA010.RA_DEPTO AS 'COD. DEPARTAMENTO',
	RTRIM(SQB010.QB_DESCRIC) AS 'DESC DEPARTAMENTO',
	RTRIM(SRA010.RA_CODUNIC) AS 'CODIGO UNICO',
	SRA010.RA_HRSDIA AS 'HORAS DIA',
	CASE SRA010.RA_ADCPERI
		WHEN  '1' THEN 'NÃO'
		WHEN  '2' THEN 'SIM'
		ELSE 'NÃO DECLARADO'
	END AS 'POSSUI PERICULOSIDADE',
	CASE SRA010.RA_ADCINS
		WHEN  '1' THEN 'NÃO'
		WHEN  '2' THEN 'SIM'
		ELSE 'NÃO DECLARADO'
	END AS 'POSSUI INSALUBRIDADE',
	SRA010.RA_VALEALI AS 'CODIGO VALE ALIMENTACAO',
	SRA010.RA_VALEREF AS 'CODIGO VALE REFEIÇÃO',
	CASE SRA010.RA_CTPCD
		WHEN  '1' THEN 'SIM'
		WHEN  '2' THEN 'NÃO'
		ELSE 'NÃO DECLARADO'
	END AS 'É PDC?',
	CASE RTRIM(COALESCE(SRA010.RA_DTVTEST,'')) WHEN ''  THEN NULL ELSE CONVERT(DATETIME, SRA010.RA_DTVTEST, 112)END AS 'DT VENCTO ESTABILIDADE',
	RTRIM(RA_PORTDEF) AS 'PORTADOR DEFICIENCIA',
	(
		SELECT SUM(RG2_VALCAL)
		FROM RG2010
		WHERE
			RG2010.D_E_L_E_T_<>'*' AND
			RG2010.RG2_MAT = SRA010.RA_MAT AND
			RG2010.RG2_PERIOD = @ANOMES
	) AS 'VAL V.A.'
FROM PROTHEUS.dbo.SRA010 SRA010
	LEFT JOIN PROTHEUS.dbo.CTT010 CTT010 ON SRA010.RA_CC=CTT010.CTT_CUSTO AND CTT010.D_E_L_E_T_<>'*'
	LEFT JOIN PROTHEUS.dbo.SRJ010 SRJ010 ON SRA010.RA_CODFUNC=SRJ010.RJ_FUNCAO AND SRJ010.D_E_L_E_T_<>'*'
	LEFT JOIN PROTHEUS.dbo.RCE010 RCE010 ON SRA010.RA_SINDICA=RCE010.RCE_CODIGO AND RCE010.D_E_L_E_T_<>'*'
	LEFT JOIN PROTHEUS.dbo.SR6010 SR6010 ON SRA010.RA_TNOTRAB=SR6010.R6_TURNO AND SR6010.D_E_L_E_T_<>'*'
	LEFT JOIN PROTHEUS.dbo.SQB010 SQB010 ON SRA010.RA_DEPTO=SQB010.QB_DEPTO AND SQB010.D_E_L_E_T_<>'*'
WHERE
	(SRA010.RA_NOME LIKE '%tHiago%' or
	 SRA010.RA_NOME LIKE '%GILBERTO MIRANDA%')
    AND (CTT010.CTT_DESC01 LIKE '%AMPLA%')
	AND
  RTRIM(SRA010.RA_SITFOLH)=''

--RFO010 Cadastro de benefícios
--SR0010 Itens de Benefícios
--RG2010 Histórico de Benefícios
--SZC010 Headcount Endicon