--TODO: Revisar query. Aparentemente o resultado apresenta multiplicidade de linhas.

WITH APROVACOES AS (
	SELECT

	    --DADOS SC
		SC1010.C1_NUM AS 'NUM SC',
		SC1010.C1_ITEM AS 'ITENS',
		SC1010.C1_VTOTAL AS 'VAL TOTAL',

	    --APROVADORES
		SC1010.C1_APROV1 AS 'APROVADOR 1',
		SC1010.C1_APROV2 AS 'APROVADOR 2',
		SC1010.C1_APROV3 AS 'APROVADOR 3',
		SC1010.C1_APROV4 AS 'APROVADOR 4',
		SC1010.C1_APROV5 AS 'APROVADOR 5',
		SC1010.C1_APROV6 AS 'APROVADOR 6',
		SC1010.C1_APROV7 AS 'APROVADOR 7',

	    --DATAS DO PROCESSO
	    CONVERT(DATETIME, IIF(SC1010.C1_ALTDATA>SC1010.C1_EMISSAO, SC1010.C1_ALTDATA, SC1010.C1_EMISSAO), 112) AS 'INICIO PROCESSO',
		Case RTrim(Coalesce(SC1010.C1_DTLIB1,'')) WHEN ''  THEN Null ELSE convert(datetime, SC1010.C1_DTLIB1, 112)END AS 'DT LIBERADO1',
		Case RTrim(Coalesce(SC1010.C1_DTLIB2,'')) WHEN ''  THEN Null ELSE convert(datetime, SC1010.C1_DTLIB2, 112)END AS 'DT LIBERADO2',
		Case RTrim(Coalesce(SC1010.C1_DTLIB3,'')) WHEN ''  THEN Null ELSE convert(datetime, SC1010.C1_DTLIB3, 112)END AS 'DT LIBERADO3',
		Case RTrim(Coalesce(SC1010.C1_DTLIB4,'')) WHEN ''  THEN Null ELSE convert(datetime, SC1010.C1_DTLIB4, 112)END AS 'DT LIBERADO4',
		Case RTrim(Coalesce(SC1010.C1_DTLIB5,'')) WHEN ''  THEN Null ELSE convert(datetime, SC1010.C1_DTLIB5, 112)END AS 'DT LIBERADO5',
		Case RTrim(Coalesce(SC1010.C1_DTLIB6,'')) WHEN ''  THEN Null ELSE convert(datetime, SC1010.C1_DTLIB6, 112)END AS 'DT LIBERADO6',
		Case RTrim(Coalesce(SC1010.C1_DTLIB7,'')) WHEN ''  THEN Null ELSE convert(datetime, SC1010.C1_DTLIB7, 112)END AS 'DT LIBERADO7',

	    --CHECK APROVAÇÃO
	    SC1010.C1_LIBOK1 AS 'APROVACAO 1',
		SC1010.C1_LIBOK2 AS 'APROVACAO 2',
		SC1010.C1_LIBOK3 AS 'APROVACAO 3',
		SC1010.C1_LIBOK4 AS 'APROVACAO 4',
		SC1010.C1_LIBOK5 AS 'APROVACAO 5',
		SC1010.C1_LIBOK6 AS 'APROVACAO 6',
		SC1010.C1_LIBOK7 AS 'APROVACAO 7'

	FROM PROTHEUS.dbo.SC1010 SC1010
	WHERE
		(SC1010.D_E_L_E_T_<>'*') 
		AND (SC1010.C1_EMISSAO>='20190101' AND SC1010.C1_EMISSAO<=GETDATE())
		AND (SC1010.C1_RESIDUO = ' ')
		-- AND (SC1010.C1_QUJE=SC1010.C1_QUANT)
		-- AND (SC1010.C1_FILIAL = '12')
		-- AND (SC1010.C1_LOCAL = '90')
		AND (SC1010.C1_APROV='L') --OR SC1010.C1_APROV='B')
		-- AND (SC1010.C1_CC = '         ')
		-- AND SC1010.C1_CLVL <> '001'
		-- AND SY1010.Y1_USER IN ('000044','000053')
	-- ORDER BY
		-- SC1010.C1_NUM, SC1010.C1_ITEM DESC
), AP_AGG AS
(
	SELECT
	    AP."NUM SC" AS 'NUM SC',
        COUNT(AP."ITENS") AS 'QT ITENS',
	    SUM(AP."VAL TOTAL") AS 'VAL TOTAL',

	    AP."APROVADOR 1" AS 'APROVADOR 1',
		AP."APROVADOR 2" AS 'APROVADOR 2',
		AP."APROVADOR 3" AS 'APROVADOR 3',
		AP."APROVADOR 4" AS 'APROVADOR 4',
		AP."APROVADOR 5" AS 'APROVADOR 5',
		AP."APROVADOR 6" AS 'APROVADOR 6',
		AP."APROVADOR 7" AS 'APROVADOR 7',

	    AP."DT LIBERADO1" AS 'DT LIBERADO1',
		AP."DT LIBERADO2" AS 'DT LIBERADO2',
		AP."DT LIBERADO3" AS 'DT LIBERADO3',
		AP."DT LIBERADO4" AS 'DT LIBERADO4',
		AP."DT LIBERADO5" AS 'DT LIBERADO5',
		AP."DT LIBERADO6" AS 'DT LIBERADO6',
		AP."DT LIBERADO7" AS 'DT LIBERADO7',

	    IIF(AP."APROVACAO 1"='S', DATEDIFF(DAY, AP."INICIO PROCESSO", AP."DT LIBERADO1"), NULL) AS 'TP APROV 1',
		IIF(AP."APROVACAO 2"='S', DATEDIFF(DAY, AP."DT LIBERADO1", AP."DT LIBERADO2"), NULL) AS 'TP APROV 2',
		IIF(AP."APROVACAO 3"='S', DATEDIFF(DAY, AP."DT LIBERADO2", AP."DT LIBERADO3"), NULL) AS 'TP APROV 3',
		IIF(AP."APROVACAO 4"='S', DATEDIFF(DAY, AP."DT LIBERADO3", AP."DT LIBERADO4"), NULL) AS 'TP APROV 4',
		IIF(AP."APROVACAO 5"='S', DATEDIFF(DAY, AP."DT LIBERADO4", AP."DT LIBERADO5"), NULL) AS 'TP APROV 5',
		IIF(AP."APROVACAO 6"='S', DATEDIFF(DAY, AP."DT LIBERADO5", AP."DT LIBERADO6"), NULL) AS 'TP APROV 6',
		IIF(AP."APROVACAO 7"='S', DATEDIFF(DAY, AP."DT LIBERADO6", AP."DT LIBERADO7"), NULL) AS 'TP APROV 7'
	FROM APROVACOES AS AP
	GROUP BY
		AP."NUM SC",

	    AP."APROVADOR 1",
		AP."APROVADOR 2",
		AP."APROVADOR 3",
		AP."APROVADOR 4",
		AP."APROVADOR 5",
		AP."APROVADOR 6",
		AP."APROVADOR 7",

		AP."DT LIBERADO1",
		AP."DT LIBERADO2",
		AP."DT LIBERADO3",
		AP."DT LIBERADO4",
		AP."DT LIBERADO5",
		AP."DT LIBERADO6",
		AP."DT LIBERADO7",

		IIF(AP."APROVACAO 1"='S', DATEDIFF(DAY, AP."INICIO PROCESSO", AP."DT LIBERADO1"), NULL),
		IIF(AP."APROVACAO 2"='S', DATEDIFF(DAY, AP."DT LIBERADO1", AP."DT LIBERADO2"), NULL),
		IIF(AP."APROVACAO 3"='S', DATEDIFF(DAY, AP."DT LIBERADO2", AP."DT LIBERADO3"), NULL),
		IIF(AP."APROVACAO 4"='S', DATEDIFF(DAY, AP."DT LIBERADO3", AP."DT LIBERADO4"), NULL),
		IIF(AP."APROVACAO 5"='S', DATEDIFF(DAY, AP."DT LIBERADO4", AP."DT LIBERADO5"), NULL),
		IIF(AP."APROVACAO 6"='S', DATEDIFF(DAY, AP."DT LIBERADO5", AP."DT LIBERADO6"), NULL),
		IIF(AP."APROVACAO 7"='S', DATEDIFF(DAY, AP."DT LIBERADO6", AP."DT LIBERADO7"), NULL)
)

SELECT
	AP_AGG."APROVADOR 1",
	AP_AGG."NUM SC",
	AP_AGG."DT LIBERADO1",
	AP_AGG."TP APROV 1",
	'1-PRIMEIRO' AS 'ESCALA APROVADOR'
FROM AP_AGG
WHERE AP_AGG."DT LIBERADO1" IS NOT NULL

UNION ALL

SELECT
	AP_AGG."APROVADOR 2",
	AP_AGG."NUM SC",
	AP_AGG."DT LIBERADO2",
	AP_AGG."TP APROV 2",
	'2-SEGUNDO' AS 'ESCALA APROVADOR'
FROM AP_AGG
WHERE AP_AGG."DT LIBERADO2" IS NOT NULL

UNION ALL

SELECT
	AP_AGG."APROVADOR 3",
	AP_AGG."NUM SC",
	AP_AGG."DT LIBERADO3",
	AP_AGG."TP APROV 3",
	'3-TERCEIRO' AS 'ESCALA APROVADOR'
FROM AP_AGG
WHERE AP_AGG."DT LIBERADO3" IS NOT NULL

UNION ALL

SELECT
	AP_AGG."APROVADOR 4",
	AP_AGG."NUM SC",
	AP_AGG."DT LIBERADO4",
	AP_AGG."TP APROV 4",
	'4-QUARTO' AS 'ESCALA APROVADOR'
FROM AP_AGG
WHERE AP_AGG."DT LIBERADO4" IS NOT NULL

UNION ALL

SELECT
	AP_AGG."APROVADOR 5",
	AP_AGG."NUM SC",
	AP_AGG."DT LIBERADO5",
	AP_AGG."TP APROV 5",
	'5-QUINTO' AS 'ESCALA APROVADOR'
FROM AP_AGG
WHERE AP_AGG."DT LIBERADO5" IS NOT NULL

UNION ALL

SELECT
	AP_AGG."APROVADOR 6",
	AP_AGG."NUM SC",
	AP_AGG."DT LIBERADO6",
	AP_AGG."TP APROV 6",
	'6-SEXTO' AS 'ESCALA APROVADOR'
FROM AP_AGG
WHERE AP_AGG."DT LIBERADO6" IS NOT NULL

UNION ALL

SELECT
	AP_AGG."APROVADOR 7",
	AP_AGG."NUM SC",
	AP_AGG."DT LIBERADO7",
	AP_AGG."TP APROV 7",
	'7-SETIMO' AS 'ESCALA APROVADOR'
FROM AP_AGG
WHERE AP_AGG."DT LIBERADO7" IS NOT NULL