SELECT
	--DADOS DE FILIAL E ARMAZÉM
	SD2010.D2_FILIAL AS 'FILIAL-DE',
	SD2010.D2_LOCAL AS 'LOCAL-DE',
	SD2010.D2_FILIAL+SD2010.D2_LOCAL+' - '+RTRIM(ARMAZEM_DE.Z01_DESC) AS 'DESCRIÇÃO ARMAZÉM-DE',
	CASE WHEN SD2010.D2_TIPO = 'D' THEN 'ENTRADA: DEVOLUÇÃO TRANSF EXTER' ELSE 'SAÍDA: TRANSF EXTER' END AS 'TIPO DE MOVIMENTO',

	--DADOS DE PRODUTO
	RTRIM(SD2010.D2_COD) AS 'CODIGO',
	RTRIM(SB1010.B1_DESC) AS 'DESCRIÇÃO',
	SD2010.D2_ITEM AS 'ITEM',
	SD2010.D2_UM AS 'UND',
	CASE WHEN SD2010.D2_TIPO = 'D' THEN SD2010.D2_QUANT ELSE SD2010.D2_QUANT*-1 END AS 'QTDE',
	SD2010.D2_PRCVEN AS 'VAL UND', --O PREÇO UTILIZADO É O PREÇO DE VENDA
	CASE WHEN SD2010.D2_TIPO = 'D' THEN SD2010.D2_TOTAL ELSE SD2010.D2_TOTAL*-1 END AS 'VAL TOTAL',

	--DADOS DE CLASSIFICAÇÃO
	SD2010.D2_TES+'-'+RTRIM(TES_SAIDA.F4_TEXTO) AS 'DESCRIÇÃO TES-DE',
	SD2010.D2_CF+'-'+RTRIM(CFOP_SAIDA.X5_DESCRI) AS 'DESCRIÇÃO CFOP-DE',

	--INFO ADICIONAIS
	SD2010.D2_PESO AS 'PESO',
	SD2010.D2_EST AS 'ESTADO DE DESTINO',
	SD2010.D2_TIPO AS 'TIPO NF',
	SD2010.D2_NFORI AS 'NF DA DEVOLUÇÃO',

	--INFO DO PEDIDO DE VENDA
	SD2010.D2_PEDIDO AS 'NUM PV',
	SD2010.D2_ITEMPV AS 'ITEM PV',
	RTRIM(SC5010.C5_USUINL) AS 'USER PV',
	RTRIM(SC5010.C5_MENNOTA) AS 'OBS PV',
	CASE WHEN SD2010.D2_SERIE='40' THEN 'FILIAL->FILIAL' ELSE 'MATRIZ->FILIAL' END AS 'TIPO TRANSF',
	SC5010.C5_FILIAL+SC6010.C6_LOCAL +'->'+ SC5010.C5_FILDEST+SC5010.C5_LOCDEST AS 'DE->PARA',
	CASE
		WHEN SC5010.C5_TIPO = 'N' THEN 'NORMAL' --Tipo de nota que se enquadra na situação padrão de venda.
		WHEN SC5010.C5_TIPO = 'D' THEN 'DEVOLUÇÃO DE COMPRAS' --Utiliza-se quando há necessidade de efetuar a devolução de mercadoria.
		WHEN SC5010.C5_TIPO = 'N' THEN 'COMPLEMENTO: PREÇOS/QUANTIDADES' --Quando existe a necessidade de complementar alguma Nota Fiscal
		WHEN SC5010.C5_TIPO = 'P' THEN 'COMPLEMENTO: IPI' --Este tipo de nota é necessária quando a alíquota ou o valor do IPI da nota fiscal foi registrado menor do que o devido.
		WHEN SC5010.C5_TIPO = 'I' THEN 'COMPLEMENTO: ICMS' --Este tipo de nota é necessária quando a alíquota ou o valor do ICMS da Nota Fiscal foi registrado menor do que o devido.
		WHEN SC5010.C5_TIPO = 'B' THEN 'BENEFICIAMENTO' --Utiliza fornecedor e Operação Beneficiamento
		/* 
			LEMBRETE DE TIPOS DE BENEFICIAMENTO
			
			Devolução ou Remessa no Poder de Terceiros (de acordo com o TES utilizado)
			Remessa na Entrada: é uma remessa de seu cliente
			Remessa na Saída: é uma remessa ao seu fornecedor
			Devolução na Entrada: é uma devolução de remessa já realizada ao seu fornecedor
			Devolução na Saída: é uma devolução de remessa já realizada pelo seu cliente
			
			Operação beneficiamento
			Quando é enviado determinado produto para guarda/conserto/beneficiamento em terceiros, o sistema disponibiliza um controle sobre estas quantidades.
			O sistema controla a quantidade de terceiros em poder da empresa e a quantidade da empresa em poder de terceiros.
			Em poder de terceiros temos dois casos básicos: 1 - Com movimentação do estoque; 2 - Sem movimentação do estoque;
			
			INFO: http://tdn.totvs.com/display/public/PROT/Pedidos+de+Venda+-+MATA410+-+Faturamento+-+P12#PedidosdeVenda-MATA410-Faturamento-P12-MapaMental
		*/
		ELSE 'ERRO'
	END AS 'TIPO PV',
	CONVERT(VARCHAR(MAX), CONVERT(VARBINARY(MAX), SC5010.C5_DSCSERV)) AS 'DESC. SERVIÇO',

	--DOCUMENTO NF DA TRANSFERÊNCIA
	RTRIM(SD2010.D2_DOC) AS 'DOCUMENTO',
	RTRIM(SD2010.D2_SERIE) 'SERIE',
	SD2010.D2_CLIENTE AS 'CLIENTE',
	SD2010.D2_LOJA AS 'LOJA',
	CASE WHEN SD2010.D2_TIPO = 'D' THEN SA2010.A2_NREDUZ ELSE SA1010.A1_NREDUZ END AS 'NOME CLIENTE',
	CASE WHEN SD2010.D2_TIPO = 'D' THEN SA2010.A2_TIPO ELSE SA1010.A1_PESSOA END AS 'PESSOA JUR\FIS',
	CASE WHEN SD2010.D2_TIPO = 'D' THEN SA2010.A2_CGC ELSE SA1010.A1_CGC END AS 'CNPJ\CPF',

	--DADOS DE GRUPO DE PRODUTO
	SD2010.D2_GRUPO+'-'+RTRIM(SBM010.BM_DESC) AS 'DESC GRUPO',

	Case RTrim(Coalesce(SD2010.D2_EMISSAO,'')) WHEN ''  THEN Null ELSE convert(datetime,SD2010.D2_EMISSAO, 112)END AS 'DT EMISSÃO DOC DE',

	CASE SD2010.D2_ESTOQUE
		WHEN 'S' THEN 'SIM'
		WHEN 'N' THEN 'NÃO'
		ELSE 'ERRO'
	END AS 'MOV ESTOQUE',

	CASE SC5010.C5_PRENF
		WHEN 'S' THEN 'SIM'
		WHEN 'N' THEN 'NÃO'
		ELSE 'ERRO'
	END AS 'GERA PRENOTA',

	--DADOS DE CABEÇALHO DA NF DE ENTRADA
	NF_ENT_CABE.*,

	--DADOS DE ITENS DAS NOTAS FISCAIS DE ENTRADA (PRÉ NOTA)
	SD1010.D1_FILIAL AS 'FILIAL PARA',
	SD1010.D1_LOCAL AS 'LOCAL PARA',
	SD1010.D1_TES AS 'TES PARA',
	SD1010.D1_CC AS 'CENTRO DE CUSTO PARA',
	CASE WHEN ISNUMERIC(SD1010.D1_TES) = 1 THEN 'CLASSIFICADA' ELSE 'NÃO CLASSIFICADA' END AS 'CLASSIFICAÇÃO',
	-- CASE WHEN SD1010.D1_TES = '   ' OR SD1010.D1_TES = '' THEN 'NÃO CLASSIFICADA' ELSE 'CLASSIFICADA' END AS 'CLASSIFICAÇÃO',
	CASE WHEN SD1010.D1_CONTA = '                    ' THEN 'ATIVO FIXO' ELSE RTRIM(SD1010.D1_CONTA) END AS 'DESC CONT CONTÁBIL',
	CASE WHEN SD1010.D1_CC = '         ' THEN 'PROCESSO PARA ARMAZÉM' ELSE RTRIM(SD1010.D1_CC) END AS 'DESCRIÇÃO CENTRO DE CUSTO'
FROM PROTHEUS.dbo.SD2010 SD2010
	LEFT JOIN PROTHEUS.dbo.Z01010 ARMAZEM_DE ON ARMAZEM_DE.Z01_CODGER=(SD2010.D2_FILIAL+SD2010.D2_LOCAL) AND ARMAZEM_DE.D_E_L_E_T_<>'*' --LINK ARMAZÉM ORIGEM
	LEFT JOIN PROTHEUS.dbo.SF4010 TES_SAIDA ON TES_SAIDA.F4_CODIGO=SD2010.D2_TES AND TES_SAIDA.D_E_L_E_T_<>'*' --LINK COM TES DE CLASSIFICAÇÃO ORIGEM
	LEFT JOIN PROTHEUS.dbo.SB1010 SB1010 ON SB1010.B1_COD=SD2010.D2_COD AND SB1010.D_E_L_E_T_<>'*' -- LINK DESCRIÇÃO PRODUTO
	LEFT JOIN PROTHEUS.dbo.SX5010 CFOP_SAIDA ON CFOP_SAIDA.X5_TABELA='13' AND CFOP_SAIDA.X5_CHAVE=TES_SAIDA.F4_CF AND CFOP_SAIDA.D_E_L_E_T_<>'*' --LINK DE CFOP ORIGEM
	LEFT JOIN PROTHEUS.dbo.SA1010 SA1010 ON SA1010.A1_COD=SD2010.D2_CLIENTE AND SA1010.A1_LOJA=SD2010.D2_LOJA AND SA1010.D_E_L_E_T_<>'*' --TABELA DE CLIENTES (SAÍDA: P NF'S DE TRANSFERÊNCIA)
	LEFT JOIN PROTHEUS.dbo.SA2010 SA2010 ON SA2010.A2_COD=SD2010.D2_CLIENTE AND SA2010.A2_COD=SD2010.D2_LOJA AND SA2010.D_E_L_E_T_<>'*' --TABELA DE FORNECEDORES (ENTRADA: P/ NF'S DE DEVOLUÇÃO)
	LEFT JOIN PROTHEUS.dbo.SBM010 SBM010 ON SB1010.B1_GRUPO=SBM010.BM_GRUPO AND SBM010.D_E_L_E_T_<>'*' --LINK DE GRUPO DE PRODUTO
	--LINK COM O CABEÇALHO DO PV
	LEFT JOIN PROTHEUS.dbo.SC5010 SC5010 ON SC5010.C5_NUM=SD2010.D2_PEDIDO AND SD2010.D2_FILIAL=SC5010.C5_FILIAL AND SC5010.D_E_L_E_T_<>'*'
	--LINK COM CORPO DO PV
	LEFT JOIN PROTHEUS.dbo.SC6010 SC6010 ON SC6010.C6_FILIAL=SD2010.D2_FILIAL AND SC6010.C6_LOCAL = SD2010.D2_LOCAL AND SD2010.D2_PEDIDO = SC6010.C6_NUM AND SD2010.D2_ITEMPV = SC6010.C6_ITEM AND SC6010.D_E_L_E_T_<>'*'
	--LINK COM O CABEÇALHO DA NF SAÍDA
	LEFT JOIN PROTHEUS.dbo.SF2010 SF2010 ON SF2010.F2_DOC=SD2010.D2_DOC AND SF2010.F2_SERIE=SD2010.D2_SERIE AND SF2010.F2_CLIENTE=SD2010.D2_CLIENTE AND SF2010.F2_LOJA=SD2010.D2_LOJA AND SF2010.D_E_L_E_T_<>'*'
	--LINK COM O CABEÇALHO DA NF ENTRADA
	LEFT JOIN (
		SELECT
			SF1010.F1_FILIAL AS 'FILIAL PARA',
			SF1010.F1_DOC AS 'DOC PARA',
			SF1010.F1_SERIE AS 'SERIE PN',
			FORN.A2_COD 'FORNECEDOR',
			FORN.A2_LOJA AS 'LOJA FORNECEDOR',
			FORN.A2_CGC AS 'CNPJ FORNECEDOR',
			SF1010.F1_NMCLASS 'USER CLASSIFICAÇÃO', --USUÁRIO CLASSIFICOU
			Case RTrim(Coalesce(SF1010.F1_DTDIGIT,'')) WHEN ''  THEN Null ELSE convert(datetime,SF1010.F1_DTDIGIT, 112)END AS 'DT DIGITAÇÃO', --DT EM QUE OCORREU A CLASSIFICAÇÃO
			Case RTrim(Coalesce(SF1010.F1_DTINCL,'')) WHEN ''  THEN Null ELSE convert(datetime,SF1010.F1_DTINCL, 112)END AS 'DT INCLUSÃO',
			Case RTrim(Coalesce(SF1010.F1_DTLANC,'')) WHEN ''  THEN Null ELSE convert(datetime,SF1010.F1_DTLANC, 112)END AS 'DT CLASSIFICAÇÃO',  --DT DA CONTABILIZAÇÃO
			Case RTrim(Coalesce(SF1010.F1_RECBMTO,'')) WHEN ''  THEN Null ELSE convert(datetime,SF1010.F1_RECBMTO, 112)END AS 'DT RECEBIMENTO', --DT EM QUE O MATERIAL FOI RECEBIDO
			SF1010.F1_NMUSER 'USER INCLUSÃO PN', --USUÁRIO INCLUIU PRENOTA
			SF1010.F1_LOGNF AS 'HISTORICO NF',
			SF1010.F1_OBS AS 'OBS PN', --OBS. PRE-NOTA
			SF1010.F1_MOTRET AS 'MOT REJEIÇÃO', --MOT. RETORNO
			SF1010.F1_OBSCLA AS 'OBS CLASSIFICAÇÃO', --OBS. CLASSIF
			SF1010.F1_ESPECIE AS 'ESPECIE DOC PN' --ESPEC. DOC
		FROM PROTHEUS.dbo.SF1010 SF1010
			LEFT JOIN PROTHEUS.dbo.SA2010 FORN ON SF1010.F1_FORNECE = FORN.A2_COD AND SF1010.F1_LOJA = FORN.A2_LOJA AND FORN.D_E_L_E_T_<>'*'
		WHERE
		SF1010.D_E_L_E_T_<>'*'
	) AS NF_ENT_CABE ON NF_ENT_CABE."DOC PARA"=SD2010.D2_DOC AND NF_ENT_CABE."SERIE PN"=SD2010.D2_SERIE AND NF_ENT_CABE."CNPJ FORNECEDOR"=SA1010.A1_CGC --TODO: a amarração por CNPJ não considera NF de entrada (Necessário incluir amarração com fornecedor, não somente cliente)
	--LINK COM O CORPO DA NF ENTRADA
	LEFT JOIN PROTHEUS.dbo.SD1010 SD1010 ON SD1010.D1_DOC=SD2010.D2_DOC AND SD1010.D1_SERIE=SD2010.D2_SERIE AND RIGHT(SD1010.D1_ITEM,2)=SD2010.D2_ITEM AND NF_ENT_CABE.FORNECEDOR=SD1010.D1_FORNECE AND NF_ENT_CABE.[LOJA FORNECEDOR]=SD1010.D1_LOJA AND SD1010.D_E_L_E_T_<>'*'
WHERE
	(SD2010.D_E_L_E_T_<>'*') AND --DESCONSIDERA DELETADOS
	(SD2010.D2_FILIAL<>'01') AND --DESCONSIDERA FATURAMENTO NA FILIAL 01
	(SD2010.D2_EMISSAO>='20170101') AND (SD2010.D2_EMISSAO<='20180228')--FIXA PERÍODO
	AND SD2010.D2_ESTOQUE = 'S' --CONSIDERA APENAS PV'S QUE ATUALIZAM ESTOQUE
ORDER BY
	SD2010.D2_EMISSAO,
	SD2010.D2_DOC,
	SD2010.D2_ITEM

/* LEMBRETE DE RELAÇÕES ENTRE AS TABELAS */

--CABEÇALHO PV: SC5 >>SINTÉTICO
--CORPO PV: SC6 >>ANALÍTICO

--CABEÇALHO DOC SAÍDA: SF2 >>SINTÉTICO
--CORPO DOC SAÍDA: SD2 >>ANALÍTICO

--CABEÇALHO DOC ENTRADA: SF1 >>SINTÉTICO
--CORPO DOC ENTRADA: SD1 >>ANALÍTICO